
[env]
TERM = "xterm-256color"


[font]

normal.family = "Cascadia Code NF" #"Cascadia Code PL"
bold.family = "Cascadia Code NF"
italic.family = "Cascadia Code NF"
bold_italic.family = "Cascadia Code NF"

size = 14.0

[window]
opacity = 0.9

padding.x = 0
padding.y = 5

decorations = "None"
decorations_theme_variant = "Dark"

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
